### ISSUE TITLE
HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by zeus1921** [ptnguyen128/downloadTwitter#1]
getting tweets before 1034706590413320192
...695 tweets fetched so far
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\downloadTwitter-master\twitter_download.py", line 146, in <module>
    main()
  File "C:\Users\Administrator\Desktop\downloadTwitter-master\twitter_download.py", line 140, in main
    download_images(urls, outdir)
  File "C:\Users\Administrator\Desktop\downloadTwitter-master\twitter_download.py", line 110, in download_images
    wget.download(url +":orig", out = output_folder+'/'+file_name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\wget.py", line 526, in download
    (tmpfile, headers) = ulib.urlretrieve(binurl, tmpfile, callback)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

whats the prb?

**Comment by sujoybhatt** [comment]
This can be fixed by changing:
`wget.download(url +":orig", out = output_folder+'/'+file_name)`
to
`wget.download(url , out = output_folder+'/'+file_name)`
